# Dockerfile

# ===== Base =====
FROM node:22-slim AS base

WORKDIR /frontend

RUN corepack enable

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

# ===== Build Stage =====
FROM base AS build

WORKDIR /frontend

RUN corepack enable

COPY --from=base /frontend/node_modules ./node_modules
COPY . .

RUN pnpm build

# ===== Final Stage =====
FROM caddy:2-alpine AS release

COPY Caddyfile /etc/caddy/Caddyfile
COPY --from=build /frontend/dist /usr/share/caddy


EXPOSE 80
