version: "3.9"

services:
  # ===== Traefik =====
  traefik:
    image: traefik:latest

    command:
      - "--api=true"
      - "--api.dashboard=true"
      - --log.level=DEBUG

      # Swarm Provider
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=traefik-public"

      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # Local TLS
      - "--tls.stores.default.defaultCertificate.certFile=/certs/cert.pem"
      - "--tls.stores.default.defaultCertificate.keyFile=/certs/key.pem"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./certs/cert.pem:/certs/cert.pem:ro"
      - "./certs/key.pem:/certs/key.pem:ro"

    deploy:
      placement:
        constraints:
          - node.role == manager

    networks:
      - traefik-public

  # ===== Vue =====
  frontend:
    build:
      context: ./frontend

    image: vue:latest

    deploy:
      replicas: 1
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.frontend.rule=Host(`example.com`)"
        - "traefik.http.routers.frontend.entrypoints=websecure"
        - "traefik.docker.network=traefik-public"

    networks:
      - traefik-public
      - web

  # ===== FastAPI =====
  backend:
    build:
      context: ./backend

    image: fast-api:latest

    deploy:
      replicas: 1
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`api.example.com`)"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls=true"
        - "traefik.http.services.backend.loadbalancer.server.port=8000"
        - "traefik.docker.network=traefik-public"
        - "traefik.http.services.backend.loadbalancer.passhostheader=true"

  environment:
    # PostgreSQL
    DATABASE_URL: postgresql+asyncpg://avas:13771998@postgres:5432/shop
    # Redis
    REDIS_URL: redis://:13771998@redis:6379/0

    networks:
      - traefik-public
      # - web
      - internal

  # ===== PostgreSQL =====
  postgres:
    image: postgres:16-alpine

    environment:
      POSTGRES_USER: avas
      POSTGRES_PASSWORD: 13771998
      POSTGRES_DB: shop

    volumes:
      - pgdata:/var/lib/postgresql/data

    deploy:
      replicas: 1

    networks:
      - internal

  # ===== Redis =====
  redis:
    image: redis:7-alpine

    command: redis-server --requirepass 13771998

    volumes:
      - redisdata:/data
    deploy:
      replicas: 1

    networks:
      - internal

# ===== Network =====
networks:
  # شبکه اصلی ترافیک
  traefik-public:
    driver: overlay

  # شبکه فرانت
  web:
    driver: overlay

  # شبکه داخلی دیتابیس
  internal:
    driver: overlay
    internal: true

# ===== Volume =====
volumes:
  pgdata:
  redisdata:
