"""add pvaid to view product admin view

Revision ID: 213243837ae5
Revises: b873a808c179
Create Date: 2026-07-04 16:06:05.682314

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "213243837ae5"
down_revision: str | Sequence[str] | None = "b873a808c179"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


from app.modules.catalog.models.product_view import (
    CREATE_PRODUCT_ADMIN_VIEW_SQL,
    DROP_PRODUCT_ADMIN_VIEW_SQL,
)


def upgrade():
    op.execute(DROP_PRODUCT_ADMIN_VIEW_SQL)
    op.execute(CREATE_PRODUCT_ADMIN_VIEW_SQL)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_admin_view")
    # ### end Alembic commands ###
