"""add indexes for user get and search in product

Revision ID: 64a7e5b5e1e9
Revises: b37ca5ed2a7c
Create Date: 2026-05-11 16:19:22.501045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64a7e5b5e1e9'
down_revision: Union[str, Sequence[str], None] = 'b37ca5ed2a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_product_brand_id', 'products', ['brand_id'], unique=False)
    op.create_index('idx_product_featured_active', 'products', ['published_at'], unique=False, postgresql_where=sa.text("is_featured = true AND status = 'ACTIVE' AND deleted_at IS NULL"))
    op.create_index('idx_product_published_at', 'products', ['published_at'], unique=False)
    op.create_index('idx_product_status_deleted_created', 'products', ['status', 'deleted_at', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_product_status_deleted_created', table_name='products')
    op.drop_index('idx_product_published_at', table_name='products')
    op.drop_index('idx_product_featured_active', table_name='products', postgresql_where=sa.text("is_featured = true AND status = 'ACTIVE' AND deleted_at IS NULL"))
    op.drop_index('idx_product_brand_id', table_name='products')
    # ### end Alembic commands ###
