"""refactor search with where in OPTModel

Revision ID: 65616ad15eea
Revises: 78904a287119
Create Date: 2026-05-02 17:30:04.994632

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65616ad15eea"
down_revision: str | Sequence[str] | None = "78904a287119"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_product_category", "product_categories", type_="unique")
    op.create_unique_constraint(
        "uq_product_category", "product_categories", ["product_id", "category_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_product_category", "product_categories", type_="unique")
    # ### end Alembic commands ###
