"""add coment to product

Revision ID: 78904a287119
Revises: 3537c2efd2f2
Create Date: 2026-04-26 18:30:40.202713

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78904a287119"
down_revision: str | Sequence[str] | None = "3537c2efd2f2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_product_tag", "product_tags", ["product_id", "tag_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_product_tag", "product_tags", type_="unique")
    op.drop_constraint("uq_product_category", "product_categories", type_="unique")
    # ### end Alembic commands ###
