"""add avrage of rating and comments to admin product model

Revision ID: 80a9a5fb429f
Revises: a4c44f4c67b9
Create Date: 2026-07-04 23:45:46.604323

"""

from collections.abc import Sequence

from alembic import op

from app.modules.catalog.models.product_view import (
    CREATE_PRODUCT_ADMIN_VIEW_SQL,
    DROP_PRODUCT_ADMIN_VIEW_SQL,
)

# revision identifiers, used by Alembic.
revision: str = "80a9a5fb429f"
down_revision: str | Sequence[str] | None = "a4c44f4c67b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade():
    op.execute(DROP_PRODUCT_ADMIN_VIEW_SQL)
    op.execute(CREATE_PRODUCT_ADMIN_VIEW_SQL)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_admin_view")
    # ### end Alembic commands ###
