"""add product_id, created_at and rating to comment model

Revision ID: a4c44f4c67b9
Revises: 213243837ae5
Create Date: 2026-07-04 23:25:53.578831

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4c44f4c67b9"
down_revision: str | Sequence[str] | None = "213243837ae5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_index(op.f("ix_comments_product_user"), table_name="comments")
    op.create_index(
        "ix_comments_product_created_rating",
        "comments",
        ["product_id", "created_at", "rating"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_comments_product_created_rating", table_name="comments")
    op.create_index(
        op.f("ix_comments_product_user"),
        "comments",
        ["product_id", "user_id"],
        unique=False,
    )
    # ### end Alembic commands ###
