"""add paid to view product admin view

Revision ID: b873a808c179
Revises: cb416294388e
Create Date: 2026-07-04 15:50:27.757646

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b873a808c179"
down_revision: str | Sequence[str] | None = "cb416294388e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


from app.modules.catalog.models.product_view import (
    CREATE_PRODUCT_ADMIN_VIEW_SQL,
    DROP_PRODUCT_ADMIN_VIEW_SQL,
)


def upgrade():
    op.execute(DROP_PRODUCT_ADMIN_VIEW_SQL)
    op.execute(CREATE_PRODUCT_ADMIN_VIEW_SQL)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_admin_view")
    # ### end Alembic commands ###
