"""add OTP table for user auth

Revision ID: 1f8e195a1a9a
Revises: 90eccf76514b
Create Date: 2026-04-22 22:19:17.533353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8e195a1a9a'
down_revision: Union[str, Sequence[str], None] = '90eccf76514b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('LOGIN', 'REGISTER', 'CHANGEPHONENUMBER', name='PurposeOTP'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_phone_number'), 'otp_codes', ['phone_number'], unique=False)
    op.create_index('ix_otp_expires_at', 'otp_codes', ['expires_at'], unique=False)
    op.create_index('ix_otp_phone_purpose', 'otp_codes', ['phone_number', 'purpose'], unique=False)
    op.create_index('uq_active_otp', 'otp_codes', ['phone_number', 'purpose'], unique=True, postgresql_where=sa.text('NOT used'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_otp', table_name='otp_codes', postgresql_where=sa.text('NOT used'))
    op.drop_index('ix_otp_phone_purpose', table_name='otp_codes')
    op.drop_index('ix_otp_expires_at', table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_phone_number'), table_name='otp_codes')
    op.drop_table('otp_codes')
    # ### end Alembic commands ###
