"""rebuild migrations

Revision ID: 3537c2efd2f2
Revises: 
Create Date: 2026-04-26 14:21:12.304227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3537c2efd2f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_unique_attribute_slug_not_null', 'attributes', ['slug'], unique=True, postgresql_where=sa.text('slug is not null'))
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_unique_brand_slug_not_null', 'brands', ['slug'], unique=True, postgresql_where=sa.text('slug is not null'))
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unique_category_slug_not_null', 'categories', ['slug'], unique=True, postgresql_where=sa.text('slug is not null'))
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Enum('LOGIN', 'REGISTER', 'RESET', name='PurposeOTP'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_codes_phone_number'), 'otp_codes', ['phone_number'], unique=False)
    op.create_index('ix_otp_expires_at', 'otp_codes', ['expires_at'], unique=False)
    op.create_index('ix_otp_phone_purpose', 'otp_codes', ['phone_number', 'purpose'], unique=False)
    op.create_index('uq_active_otp', 'otp_codes', ['phone_number', 'purpose'], unique=True, postgresql_where=sa.text('NOT used'))
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_unique_tag_slug_not_null', 'tags', ['slug'], unique=True, postgresql_where=sa.text('slug is not null'))
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CUSTOMER', name='UserRole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False, comment='شناسه محصول و یک کد یکتاست'),
    sa.Column('sku', sa.String(length=100), nullable=False, comment='کد یکتای کالا در سیستم انبار داری'),
    sa.Column('slug', sa.String(length=200), nullable=True, comment='رشته مناسب آدرس سایت (برای فروشگاه حضوری می\u200cتواند خالی باشد)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='نام کالا'),
    sa.Column('description', sa.Text(), nullable=True, comment='توضیح کامل همراه با HTML'),
    sa.Column('price', sa.Integer(), nullable=False, comment='قیمت پایه کالا (واحد کوچک پول)'),
    sa.Column('discount_price', sa.Integer(), nullable=True, comment='قیمت تخفیفی کالا (واحد کوچک پول)'),
    sa.Column('cost_price', sa.Integer(), nullable=True, comment='قیمت خرید کالا (محرمانه)'),
    sa.Column('tax_rate', sa.Integer(), nullable=False, comment='نرخ مالیات به واحد صدم درصد (basis points). مثال: 900=9.00%'),
    sa.Column('currency_code', sa.String(length=3), nullable=False, comment='کد ارز (مثلاً IRR)'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DRAFT', 'ARCHIVED', name='productstatus'), nullable=False, comment='وضعیت محصول'),
    sa.Column('is_featured', sa.Boolean(), nullable=False, comment='آیا کالا شاخص است'),
    sa.Column('is_digital', sa.Boolean(), nullable=False, comment='آیا کالا دیجیتال قابل دانلود است'),
    sa.Column('weight', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('width', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('height', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('depth', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('gtin', sa.String(length=20), nullable=True, comment='شناسه جهانی کالا (GTIN/EAN/UPC)'),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('cost_price IS NULL OR cost_price >= 0', name='ck_product_cost_non_negative'),
    sa.CheckConstraint('discount_price IS NULL OR discount_price <= price', name='ck_product_discount_le_price'),
    sa.CheckConstraint('discount_price IS NULL OR discount_price >= 0', name='ck_product_discount_non_negative'),
    sa.CheckConstraint('price >= 0', name='ck_product_price_non_negative'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gtin')
    )
    op.create_index('idx_unique_product_slug_not_null', 'products', ['slug'], unique=True, postgresql_where=sa.text('slug is not null'))
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('low_stock_alert', sa.Integer(), nullable=False),
    sa.Column('allow_backorder', sa.Boolean(), nullable=False, comment='آیا فروش بدون موجودی مجاز است یا خیر'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_quantity_non_negative'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_inventory_reserved_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_inventories_id'), 'inventories', ['id'], unique=False)
    op.create_table('product_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'attribute_id', name='uq_product_attribute')
    )
    op.create_index(op.f('ix_product_attributes_attribute_id'), 'product_attributes', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_product_attributes_product_id'), 'product_attributes', ['product_id'], unique=False)
    op.create_table('product_categories',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'category_id'),
    sa.UniqueConstraint('product_id', 'category_id', name='uq_product_category')
    )
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True, comment='توضیح عکس برای سئو و دسترسی'),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='آیا این عکس تصویر اصلی محصول است'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='ترتیب نمایش عکس\u200cها'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unique_primary_image', 'product_images', ['product_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('product_tags',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'tag_id'),
    sa.UniqueConstraint('product_id', 'tag_id', name='uq_product_tag')
    )
    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True, comment='قیمت خاص واریانت (واحد کوچک پول)'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('price IS NULL OR price >= 0', name='ck_variant_price_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_product_variants_id'), 'product_variants', ['id'], unique=False)
    op.create_table('product_variant_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'attribute_id', name='uq_variant_attribute')
    )
    op.create_index(op.f('ix_product_variant_attributes_attribute_id'), 'product_variant_attributes', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_product_variant_attributes_variant_id'), 'product_variant_attributes', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_variant_attributes_variant_id'), table_name='product_variant_attributes')
    op.drop_index(op.f('ix_product_variant_attributes_attribute_id'), table_name='product_variant_attributes')
    op.drop_table('product_variant_attributes')
    op.drop_index(op.f('ix_product_variants_id'), table_name='product_variants')
    op.drop_table('product_variants')
    op.drop_table('product_tags')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_index('idx_unique_primary_image', table_name='product_images', postgresql_where=sa.text('is_primary = true'))
    op.drop_table('product_images')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_product_attributes_product_id'), table_name='product_attributes')
    op.drop_index(op.f('ix_product_attributes_attribute_id'), table_name='product_attributes')
    op.drop_table('product_attributes')
    op.drop_index(op.f('ix_inventories_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_table('comments')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index('idx_unique_product_slug_not_null', table_name='products', postgresql_where=sa.text('slug is not null'))
    op.drop_table('products')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_unique_tag_slug_not_null', table_name='tags', postgresql_where=sa.text('slug is not null'))
    op.drop_table('tags')
    op.drop_index('uq_active_otp', table_name='otp_codes', postgresql_where=sa.text('NOT used'))
    op.drop_index('ix_otp_phone_purpose', table_name='otp_codes')
    op.drop_index('ix_otp_expires_at', table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_phone_number'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index('idx_unique_category_slug_not_null', table_name='categories', postgresql_where=sa.text('slug is not null'))
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_index('idx_unique_brand_slug_not_null', table_name='brands', postgresql_where=sa.text('slug is not null'))
    op.drop_table('brands')
    op.drop_index('idx_unique_attribute_slug_not_null', table_name='attributes', postgresql_where=sa.text('slug is not null'))
    op.drop_table('attributes')
    # ### end Alembic commands ###
