"""make discount percent of product model hybrid

Revision ID: 42ac14038db2
Revises: bc9dbe7cd83d
Create Date: 2026-05-12 00:14:26.898566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42ac14038db2'
down_revision: Union[str, Sequence[str], None] = 'bc9dbe7cd83d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
