"""refactor product and variant and inventory

Revision ID: b34524d1e02b
Revises: 65616ad15eea
Create Date: 2026-05-04 13:05:57.730138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b34524d1e02b'
down_revision: Union[str, Sequence[str], None] = '65616ad15eea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('variant_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('inventories_product_id_key'), 'inventories', type_='unique')
    op.create_unique_constraint(None, 'inventories', ['variant_id'])
    op.drop_constraint(op.f('inventories_product_id_fkey'), 'inventories', type_='foreignkey')
    op.create_foreign_key(None, 'inventories', 'product_variants', ['variant_id'], ['id'])
    op.drop_column('inventories', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventories', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inventories', type_='foreignkey')
    op.create_foreign_key(op.f('inventories_product_id_fkey'), 'inventories', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'inventories', type_='unique')
    op.create_unique_constraint(op.f('inventories_product_id_key'), 'inventories', ['product_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('inventories', 'variant_id')
    # ### end Alembic commands ###
