"""add name, status, created_at and price indexes to product model

Revision ID: b37ca5ed2a7c
Revises: 59cdf9b84d71
Create Date: 2026-05-09 13:11:22.820463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37ca5ed2a7c'
down_revision: Union[str, Sequence[str], None] = '59cdf9b84d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_product_created', 'products', ['created_at'], unique=False)
    op.create_index('idx_product_name', 'products', ['name'], unique=False)
    op.create_index('idx_product_price', 'products', ['price'], unique=False)
    op.create_index('idx_product_status', 'products', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_product_status', table_name='products')
    op.drop_index('idx_product_price', table_name='products')
    op.drop_index('idx_product_name', table_name='products')
    op.drop_index('idx_product_created', table_name='products')
    # ### end Alembic commands ###
