"""add indexes for user get and search in variant, category, tag and  attribute

Revision ID: bc9dbe7cd83d
Revises: 64a7e5b5e1e9
Create Date: 2026-05-11 16:26:46.701791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9dbe7cd83d'
down_revision: Union[str, Sequence[str], None] = '64a7e5b5e1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_product_attribute_attr_value', 'product_attributes', ['attribute_id', 'value'], unique=False)
    op.create_index('idx_product_category_category_id', 'product_categories', ['category_id'], unique=False)
    op.create_index('idx_product_tag_tag_id', 'product_tags', ['tag_id'], unique=False)
    op.create_index('idx_variant_product_id', 'product_variants', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_variant_product_id', table_name='product_variants')
    op.drop_index('idx_product_tag_tag_id', table_name='product_tags')
    op.drop_index('idx_product_category_category_id', table_name='product_categories')
    op.drop_index('idx_product_attribute_attr_value', table_name='product_attributes')
    # ### end Alembic commands ###
